import 'package:flutter/material.dart';
import 'package:flutter_google_places_sdk/flutter_google_places_sdk.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';

IconData getIconForPlaceType(PlaceType placeType) {
  switch (placeType) {
    case PlaceType.OTHER:
      return FontAwesomeIcons.question;
    case PlaceType.ACCOUNTING:
      return FontAwesomeIcons.calculator;
    case PlaceType.ADMINISTRATIVE_AREA_LEVEL_1:
      return FontAwesomeIcons.locationDot;
    case PlaceType.ADMINISTRATIVE_AREA_LEVEL_2:
      return FontAwesomeIcons.locationDot;
    case PlaceType.ADMINISTRATIVE_AREA_LEVEL_3:
      return FontAwesomeIcons.locationDot;
    case PlaceType.ADMINISTRATIVE_AREA_LEVEL_4:
      return FontAwesomeIcons.locationDot;
    case PlaceType.ADMINISTRATIVE_AREA_LEVEL_5:
      return FontAwesomeIcons.locationDot;
    case PlaceType.AIRPORT:
      return FontAwesomeIcons.plane;
    case PlaceType.AMUSEMENT_PARK:
      return FontAwesomeIcons.icons;
    case PlaceType.AQUARIUM:
      return FontAwesomeIcons.fish;
    case PlaceType.ARCHIPELAGO:
      return FontAwesomeIcons.earthAmericas;
    case PlaceType.ART_GALLERY:
      return FontAwesomeIcons.paintbrush;
    case PlaceType.ATM:
      return FontAwesomeIcons.moneyBill1;
    case PlaceType.BAKERY:
      return FontAwesomeIcons.breadSlice;
    case PlaceType.BANK:
      return FontAwesomeIcons.buildingColumns;
    case PlaceType.BAR:
      return FontAwesomeIcons.champagneGlasses;
    case PlaceType.BEAUTY_SALON:
      return FontAwesomeIcons.spa;
    case PlaceType.BICYCLE_STORE:
      return FontAwesomeIcons.bicycle;
    case PlaceType.BOOK_STORE:
      return FontAwesomeIcons.book;
    case PlaceType.BOWLING_ALLEY:
      return FontAwesomeIcons.bowlingBall;
    case PlaceType.BUS_STATION:
      return FontAwesomeIcons.bus;
    case PlaceType.CAFE:
      return FontAwesomeIcons.mugSaucer;
    case PlaceType.CAMPGROUND:
      return FontAwesomeIcons.campground;
    case PlaceType.CAR_DEALER:
      return FontAwesomeIcons.car;
    case PlaceType.CAR_RENTAL:
      return FontAwesomeIcons.car;
    case PlaceType.CAR_REPAIR:
      return FontAwesomeIcons.carOn;
    case PlaceType.CAR_WASH:
      return FontAwesomeIcons.carRear;
    case PlaceType.CASINO:
      return FontAwesomeIcons.dice;
    case PlaceType.CEMETERY:
      return FontAwesomeIcons.cross;
    case PlaceType.CHURCH:
      return FontAwesomeIcons.church;
    case PlaceType.CITY_HALL:
      return FontAwesomeIcons.city;
    case PlaceType.CLOTHING_STORE:
      return FontAwesomeIcons.shirt;
    case PlaceType.COLLOQUIAL_AREA:
      return FontAwesomeIcons.locationDot;
    case PlaceType.CONTINENT:
      return FontAwesomeIcons.globe;
    case PlaceType.CONVENIENCE_STORE:
      return FontAwesomeIcons.store;
    case PlaceType.COUNTRY:
      return FontAwesomeIcons.flag;
    case PlaceType.COURTHOUSE:
      return FontAwesomeIcons.scaleBalanced;
    case PlaceType.DENTIST:
      return FontAwesomeIcons.tooth;
    case PlaceType.DEPARTMENT_STORE:
      return FontAwesomeIcons.bagShopping;
    case PlaceType.DOCTOR:
      return FontAwesomeIcons.stethoscope;
    case PlaceType.DRUGSTORE:
      return FontAwesomeIcons.pills;
    case PlaceType.ELECTRICIAN:
      return FontAwesomeIcons.boltLightning;
    case PlaceType.ELECTRONICS_STORE:
      return FontAwesomeIcons.tv;
    case PlaceType.EMBASSY:
      return FontAwesomeIcons.landmark;
    case PlaceType.ESTABLISHMENT:
      return FontAwesomeIcons.building;
    case PlaceType.FINANCE:
      return FontAwesomeIcons.moneyBill;
    case PlaceType.FIRE_STATION:
      return FontAwesomeIcons.fire;
    case PlaceType.FLOOR:
      return FontAwesomeIcons.map;
    case PlaceType.FLORIST:
      return FontAwesomeIcons.seedling;
    case PlaceType.FOOD:
      return FontAwesomeIcons.utensils;
    case PlaceType.FUNERAL_HOME:
      return FontAwesomeIcons.handsPraying;
    case PlaceType.FURNITURE_STORE:
      return FontAwesomeIcons.couch;
    case PlaceType.GAS_STATION:
      return FontAwesomeIcons.gasPump;
    case PlaceType.GENERAL_CONTRACTOR:
      return FontAwesomeIcons.hammer;
    case PlaceType.GEOCODE:
      return FontAwesomeIcons.locationDot;
    case PlaceType.GROCERY_OR_SUPERMARKET:
      return FontAwesomeIcons.cartShopping;
    case PlaceType.GYM:
      return FontAwesomeIcons.dumbbell;
    case PlaceType.HAIR_CARE:
      return FontAwesomeIcons.spa;
    case PlaceType.HARDWARE_STORE:
      return FontAwesomeIcons.computerMouse;
    case PlaceType.HEALTH:
      return FontAwesomeIcons.heartPulse;
    case PlaceType.HINDU_TEMPLE:
      return FontAwesomeIcons.om;
    case PlaceType.HOME_GOODS_STORE:
      return FontAwesomeIcons.house;
    case PlaceType.HOSPITAL:
      return FontAwesomeIcons.hospital;
    case PlaceType.INSURANCE_AGENCY:
      return FontAwesomeIcons.shieldHalved;
    case PlaceType.INTERSECTION:
      return FontAwesomeIcons.rightLeft;
    case PlaceType.JEWELRY_STORE:
      return FontAwesomeIcons.gem;
    case PlaceType.LAUNDRY:
      return FontAwesomeIcons.soap;
    case PlaceType.LAWYER:
      return FontAwesomeIcons.gavel;
    case PlaceType.LIBRARY:
      return FontAwesomeIcons.bookOpen;
    case PlaceType.LIGHT_RAIL_STATION:
      return FontAwesomeIcons.train;
    case PlaceType.LIQUOR_STORE:
      return FontAwesomeIcons.wineGlass;
    case PlaceType.LOCAL_GOVERNMENT_OFFICE:
      return FontAwesomeIcons.landmark;
    case PlaceType.LOCALITY:
      return FontAwesomeIcons.locationDot;
    case PlaceType.LOCKSMITH:
      return FontAwesomeIcons.key;
    case PlaceType.LODGING:
      return FontAwesomeIcons.bed;
    case PlaceType.MEAL_DELIVERY:
      return FontAwesomeIcons.truck;
    case PlaceType.MEAL_TAKEAWAY:
      return FontAwesomeIcons.box;
    case PlaceType.MOSQUE:
      return FontAwesomeIcons.mosque;
    case PlaceType.MOVIE_RENTAL:
      return FontAwesomeIcons.video;
    case PlaceType.MOVIE_THEATER:
      return FontAwesomeIcons.film;
    case PlaceType.MOVING_COMPANY:
      return FontAwesomeIcons.truckMoving;
    case PlaceType.MUSEUM:
      return FontAwesomeIcons.monument;
    case PlaceType.NATURAL_FEATURE:
      return FontAwesomeIcons.tree;
    case PlaceType.NEIGHBORHOOD:
      return FontAwesomeIcons.locationDot;
    case PlaceType.NIGHT_CLUB:
      return FontAwesomeIcons.champagneGlasses;
    case PlaceType.PAINTER:
      return FontAwesomeIcons.paintRoller;
    case PlaceType.PARK:
      return FontAwesomeIcons.tree;
    case PlaceType.PARKING:
      return FontAwesomeIcons.squareParking;
    case PlaceType.PET_STORE:
      return FontAwesomeIcons.paw;
    case PlaceType.PHARMACY:
      return FontAwesomeIcons.suitcaseMedical;
    case PlaceType.PHYSIOTHERAPIST:
      return FontAwesomeIcons.briefcaseMedical;
    case PlaceType.PLACE_OF_WORSHIP:
      return FontAwesomeIcons.placeOfWorship;
    case PlaceType.PLUMBER:
      return FontAwesomeIcons.wrench;
    case PlaceType.PLUS_CODE:
      return FontAwesomeIcons.plus;
    case PlaceType.POINT_OF_INTEREST:
      return FontAwesomeIcons.locationDot;
    case PlaceType.POLICE:
      return Icons.local_police;
    case PlaceType.POLITICAL:
      return FontAwesomeIcons.landmark;
    case PlaceType.POST_BOX:
      return FontAwesomeIcons.envelopesBulk;
    case PlaceType.POST_OFFICE:
      return FontAwesomeIcons.envelope;
    case PlaceType.POSTAL_CODE_PREFIX:
      return FontAwesomeIcons.locationDot;
    case PlaceType.POSTAL_CODE_SUFFIX:
      return FontAwesomeIcons.locationDot;
    case PlaceType.POSTAL_CODE:
      return FontAwesomeIcons.locationDot;
    case PlaceType.POSTAL_TOWN:
      return FontAwesomeIcons.locationDot;
    case PlaceType.PREMISE:
      return FontAwesomeIcons.building;
    case PlaceType.PRIMARY_SCHOOL:
      return FontAwesomeIcons.graduationCap;
    case PlaceType.REAL_ESTATE_AGENCY:
      return FontAwesomeIcons.building;
    case PlaceType.RESTAURANT:
      return FontAwesomeIcons.utensils;
    case PlaceType.ROOFING_CONTRACTOR:
      return FontAwesomeIcons.houseChimneyCrack;
    case PlaceType.ROOM:
      return FontAwesomeIcons.bed;
    case PlaceType.ROUTE:
      return FontAwesomeIcons.route;
    case PlaceType.RV_PARK:
      return FontAwesomeIcons.campground;
    case PlaceType.SCHOOL:
      return FontAwesomeIcons.school;
    case PlaceType.SECONDARY_SCHOOL:
      return FontAwesomeIcons.graduationCap;
    case PlaceType.SHOE_STORE:
      return FontAwesomeIcons.shoePrints;
    case PlaceType.SHOPPING_MALL:
      return FontAwesomeIcons.bagShopping;
    case PlaceType.SPA:
      return FontAwesomeIcons.spa;
    case PlaceType.STADIUM:
      return Icons.stadium;
    case PlaceType.STORAGE:
      return FontAwesomeIcons.warehouse;
    case PlaceType.STORE:
      return FontAwesomeIcons.store;
    case PlaceType.STREET_ADDRESS:
      return FontAwesomeIcons.locationDot;
    case PlaceType.STREET_NUMBER:
      return FontAwesomeIcons.locationDot;
    case PlaceType.SUBLOCALITY_LEVEL_1:
      return FontAwesomeIcons.locationDot;
    case PlaceType.SUBLOCALITY_LEVEL_2:
      return FontAwesomeIcons.locationDot;
    case PlaceType.SUBLOCALITY_LEVEL_3:
      return FontAwesomeIcons.locationDot;
    case PlaceType.SUBLOCALITY_LEVEL_4:
      return FontAwesomeIcons.locationDot;
    case PlaceType.SUBLOCALITY_LEVEL_5:
      return FontAwesomeIcons.locationDot;
    case PlaceType.SUBLOCALITY:
      return FontAwesomeIcons.locationDot;
    case PlaceType.SUBPREMISE:
      return FontAwesomeIcons.building;
    case PlaceType.SUBWAY_STATION:
      return FontAwesomeIcons.trainSubway;
    case PlaceType.SUPERMARKET:
      return FontAwesomeIcons.basketShopping;
    case PlaceType.SYNAGOGUE:
      return FontAwesomeIcons.synagogue;
    case PlaceType.TAXI_STAND:
      return FontAwesomeIcons.taxi;
    case PlaceType.TOURIST_ATTRACTION:
      return FontAwesomeIcons.camera;
    case PlaceType.TOWN_SQUARE:
      return FontAwesomeIcons.locationDot;
    case PlaceType.TRAIN_STATION:
      return FontAwesomeIcons.train;
    case PlaceType.TRANSIT_STATION:
      return FontAwesomeIcons.bus;
    case PlaceType.TRAVEL_AGENCY:
      return FontAwesomeIcons.suitcase;
    case PlaceType.UNIVERSITY:
      return FontAwesomeIcons.graduationCap;
    case PlaceType.VETERINARY_CARE:
      return FontAwesomeIcons.paw;
    case PlaceType.ZOO:
      return FontAwesomeIcons.paw;
    default:
      return FontAwesomeIcons.locationDot; // Default icon
  }
}
